#!/usr/bin/env python
import time
import subprocess
import re
import logging

SCREEN_HEIGHT = 1080
PERCENT_LIMIT = 90
BAR_SIZE = 15
SHOW_CMD = '~/.config/polybar/launch.sh'
HIDE_CMD = 'killall polybar'

#subprocess.run("killall python", shell=True)
logging.basicConfig(level=logging.INFO)

def get_y_position():
    xdotool_output = subprocess.check_output(
        'xdotool getmouselocation --shell',
        shell=True).decode('utf-8')
    return int(re.search(r'Y=(\d{1,})', xdotool_output).groups()[0]) + 1

hidden = True
subprocess.call(HIDE_CMD, shell=True)
while True:
    y = get_y_position()
    time.sleep(.05)
    on_edge = y < BAR_SIZE
    logging.info("Got height %d. On edge: %s", y, str(on_edge))
    if on_edge and hidden:
        subprocess.call(SHOW_CMD, shell=True)
        hidden = False
    if (not on_edge) and (not hidden):
        subprocess.call(HIDE_CMD, shell=True)
        hidden = True
